### PR TITLE
Feature/ted 139

### PR DESCRIPTION
**Pull request by idellal**
Technical & conceptual mapping of F03

### CODE REVIEW

**Review by costezki — CHANGES_REQUESTED** [review]
* `/notices/samples` need to be distributed into corresponding `mappings/package_xx` as `./test data`
* lets rename (and take as a convention) `/transformation/mapings/output.rml.ttl` to be named `mappings.rml.ttl`, the YARRRML shall be `mappings.yarrrml.yml`. 
* `/output` folder shall contain the transformation of all sample files (and soon after, also the validation reports)

**Comment by csnyulas** [comment]
> https://github.com/meaningfy-ws/ted-sws-artefacts/pull/5#pullrequestreview-946764944
I would like to add some clarification regarding to the observation about the "`/notices/samples` need to be distributed ...". The purpose of the `notices/TED XML Samples` folder is to have a full copy of the notices that were selected by Everis (which are currently only available in GDrive) also in github. From here we can copy the appropriate forms in the `mappings\package_FXX\test_data` folders as we progress and want to do more and more tests. In case of form F03 have already copied some relevant forms to the `mappings\package_F03\test_data` (`378222_2016.xml`, `000342_2020.xml`. `000269_2020.xml`), but not all of them, to not create unnecessary delays with testing during the mapping development phase.

**Comment by idellal** [comment]
> > [#5 (review)](https://github.com/meaningfy-ws/ted-sws-artefacts/pull/5#pullrequestreview-946764944)
> 
> I would like to add some clarification regarding to the observation about the "`/notices/samples` need to be distributed ...". The purpose of the `notices/TED XML Samples` folder is to have a full copy of the notices that were selected by Everis (which are currently only available in GDrive) also in github. From here we can copy the appropriate forms in the `mappings\package_FXX\test_data` folders as we progress and want to do more and more tests. In case of form F03 have already copied some relevant forms to the `mappings\package_F03\test_data` (`378222_2016.xml`, `000342_2020.xml`. `000269_2020.xml`), but not all of them, to not create unnecessary delays with testing during the mapping development phase.

Is it the reason  why Dragos deleted this notices folder from the main branch?

**Comment by idellal** [comment]
> * `/notices/samples` need to be distributed into corresponding `mappings/package_xx` as `./test data`
> 
>     * lets rename (and take as a convention) `/transformation/mapings/output.rml.ttl` to be named `mappings.rml.ttl`, the YARRRML shall be `mappings.yarrrml.yml`.
> 
>     * `/output` folder shall contain the transformation of all sample files (and soon after, also the validation reports)

**Comment by csnyulas** [comment]
> > > [#5 (review)](https://github.com/meaningfy-ws/ted-sws-artefacts/pull/5#pullrequestreview-946764944)
> > 
> > 
> > I would like to add some clarification regarding to the observation about the "`/notices/samples` need to be distributed ...". The purpose of the `notices/TED XML Samples` folder is to have a full copy of the notices that were selected by Everis (which are currently only available in GDrive) also in github. From here we can copy the appropriate forms in the `mappings\package_FXX\test_data` folders as we progress and want to do more and more tests. In case of form F03 have already copied some relevant forms to the `mappings\package_F03\test_data` (`378222_2016.xml`, `000342_2020.xml`. `000269_2020.xml`), but not all of them, to not create unnecessary delays with testing during the mapping development phase.
> 
> Is it the reason why Dragos deleted this notices folder from the main branch?

> 

Dragos deleted the `notices` folder because he reorganized its content in the mapping packages. That was alright, and those are still there. The current content of the notices folder is new. It is not the one created by Dragos, but rather it was created by me after Dragos restructured the folders. It contains the Everis test data at the moment. I didn't want to spread the entire content of the Everis test data over the mapping packages yet, for multiple reasons. Some of it I mentioned in my earlier comment, but there are much more that went in my thinking, which I am not going to elaborate here. I would just add that I thought that it would be nice to have all the Everis them somewhere accessible in github (doesn't need to be here, if we find a better place for it), from where we can take whatever we need, and copy them in the appropriate mapping packages, as we progress through the different stages of our work.

**Pull request closed without merging**
