### PR TITLE
F03: Update conceptual & technical mappings (new ePO version and new Excel file structure)

### PR DESCRIPTION
**Pull request by idellal**

### CODE REVIEW

**Review by costezki — APPROVED** [review]

**Review by csnyulas — CHANGES_REQUESTED** [review]
According to https://prefix.cc/cpov, and https://semiceu.github.io/CPOV/releases/2.00/#rdf the namespace of the CPOV ontology, for which the prefix `cpov` stands, is:
`http://data.europa.eu/m8g`
This namespace is common for all the SEMICeu Core Vocabularies. So, `cpov` prefix will point to the same namespace as `core-voc` and `cccev`.
This should be declared as such in the [prefixes.json](https://github.com/meaningfy-ws/ted-sws/blob/main/ted_sws/resources/prefixes/prefixes.json) file, and all the RML files where it is used.

According to https://semiceu.github.io/CPOV/releases/2.00/#Contact%20Point%3Ahas%20email, the URI for the "has email" and "has telephone" properties is 
http://data.europa.eu/m8g/email, respectively http://data.europa.eu/m8g/telephone (or in short form `cpov:email` and `cpov:telephone`). Note that the local name of the property does not start with "has".
This should be fixed both in **technical mapping files** and the **ePO ontology**.

**Review by csnyulas — CHANGES_REQUESTED** [review]
As I said in my original review, we need to also change the use of `email` and `telephone` properties. `cpov:hasEmail` should be `cpov:email` and `cpov:hasTelephone` should be `cpov:telephone`. Please coordinate these changes also with @andreea-pasare so that they are implemented in EPO as well.

Why is there a second mappings folder added, called `mappings2`? Is this a mistake (perhaps a local change that was inadvertently committed), or it is on purpose?

**Comment by idellal** [comment]
> As I said in my original review, we need to also change the use of `email` and `telephone` properties. `cpov:hasEmail` should be `cpov:email` and `cpov:hasTelephone` should be 'cpov:telephone`. Please coordinate these changes also with @andreea-pasare so that they are implemented in EPO as well.
> 
> 
> 
> Why is there a second mappings folder added, called `mappings2`. Is this a mistake (perhaps a local change that was inadvertently committed), or it is on purpose.

Ok I will handle that with Andreea. I will delete the mappings2 folder it was a test with Kolea...

**Comment by andreea-pasare** [comment]
Requested changes have been implemented in ePO 3.0.0 beta as well.

**Comment by idellal** [comment]
> > Requested changes have been implemented in ePO 3.0.0 beta as well.
> 
> So, what property should be used in the RDF that we generate conform to ePO v.2.0.0: `epo:hasEmail`, `cpov:hassEmail` or `cpov:email` (and the same applies for representing the telephone number)?
> 
> Or should we write our mappings to work direclty with ePO v3.0.0 (beta)?

We are now using cpov:email & cpov:telephone for rdf generation

**Review by costezki — APPROVED** [review]

**Comment by csnyulas** [comment]
This looks very nice now.
Will the `mapping2` folder be deleted, or it needs to stay, and to be merged back into `main`.

**Review by csnyulas — APPROVED** [review]

**Pull request merged**
